"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
    nvarchar: 'String',
    int: 'Number',
    mediumint: 'Number',
    bigint: 'String',
    decimal: 'Number',
    year: 'Number',
    json: 'Array',
    text: 'String',
    tinyint: 'Number',
    tinyblob: 'String',
    mediumtext: 'String',
    mediumblob: 'String',
    longblob: 'String',
    varchar: 'String',
    timestamp: 'Date',
    datetime: 'Date',
    time: 'Date',
    enum: 'Enum',
    date: 'Date',
    double: 'Number',
    longtext: 'String',
    binary: 'String',
    float: 'Number',
    varbinary: 'String',
    char: 'String',
    blob: 'String',
    set: 'Array',
};
