export default {
    nvarchar: 'String',
    int: 'Number',
    mediumint: 'Number',
    bigint: 'String', // save bigints as strings to maintain fidelity
    decimal: 'Number',
    year: 'Number',
    json: 'Array',
    text: 'String',
    tinyint: 'Number',
    tinyblob: 'String',
    mediumtext: 'String',
    mediumblob: 'String',
    longblob: 'String',
    varchar: 'String',
    timestamp: 'Date',
    datetime: 'Date',
    time: 'Date',
    enum: 'Enum',
    date: 'Date',
    double: 'Number',
    longtext: 'String',
    binary: 'String',
    float: 'Number',
    varbinary: 'String',
    char: 'String',
    blob: 'String', // MongoDB limits blobs to under 16MB in size, so just be careful
    set: 'Array',
};
